-- migrations/000001_init_schema.up.sql

-- Create accounts table
CREATE TABLE IF NOT EXISTS accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_number VARCHAR(11) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL,
    account_type VARCHAR(20) NOT NULL CHECK (account_type IN ('checking', 'savings')),
    balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create operation_types table
CREATE TABLE IF NOT EXISTS operation_types (
    operation_type_id INTEGER PRIMARY KEY,
    description VARCHAR(100) NOT NULL
);

-- Insert operation types
INSERT INTO operation_types (operation_type_id, description) VALUES
    (1, 'Normal Purchase'),
    (2, 'Purchase with installments'),
    (3, 'Withdrawal'),
    (4, 'Credit Voucher')
ON CONFLICT (operation_type_id) DO NOTHING;

-- Create transactions table
CREATE TABLE IF NOT EXISTS transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
    operation_type_id INTEGER NOT NULL REFERENCES operation_types(operation_type_id),
    amount DECIMAL(15, 2) NOT NULL,
    balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    event_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_event_date ON transactions(event_date);
CREATE INDEX IF NOT EXISTS idx_accounts_document_number ON accounts(document_number);
CREATE INDEX IF NOT EXISTS idx_accounts_email ON accounts(email);

-- Add comments
COMMENT ON TABLE accounts IS 'Stores customer account information with enhanced fields';
COMMENT ON TABLE transactions IS 'Stores all financial transactions';
COMMENT ON TABLE operation_types IS 'Lookup table for transaction types';
COMMENT ON COLUMN accounts.account_type IS 'Type of account: checking or savings';
COMMENT ON COLUMN accounts.balance IS 'Current account balance';