// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/alexduzi/challengepismo/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAccountRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAccountRepository_Delete_Call {
	return &MockAccountRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAccountRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockAccountRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Delete_Call) Return(err error) *MockAccountRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockAccountRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetAll(ctx context.Context) ([]domain.Account, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Account, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Account); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockAccountRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountRepository_Expecter) GetAll(ctx interface{}) *MockAccountRepository_GetAll_Call {
	return &MockAccountRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockAccountRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockAccountRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetAll_Call) Return(accounts []domain.Account, err error) *MockAccountRepository_GetAll_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Account, error)) *MockAccountRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetByID(ctx context.Context, id int64) (*domain.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAccountRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAccountRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAccountRepository_GetByID_Call {
	return &MockAccountRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAccountRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockAccountRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetByID_Call) Return(account *domain.Account, err error) *MockAccountRepository_GetByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.Account, error)) *MockAccountRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Save(ctx context.Context, account domain.Account) (*domain.Account, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Account) (*domain.Account, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Account) *domain.Account); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Account) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAccountRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - account domain.Account
func (_e *MockAccountRepository_Expecter) Save(ctx interface{}, account interface{}) *MockAccountRepository_Save_Call {
	return &MockAccountRepository_Save_Call{Call: _e.mock.On("Save", ctx, account)}
}

func (_c *MockAccountRepository_Save_Call) Run(run func(ctx context.Context, account domain.Account)) *MockAccountRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Account
		if args[1] != nil {
			arg1 = args[1].(domain.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Save_Call) Return(account1 *domain.Account, err error) *MockAccountRepository_Save_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountRepository_Save_Call) RunAndReturn(run func(ctx context.Context, account domain.Account) (*domain.Account, error)) *MockAccountRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Update(ctx context.Context, account domain.Account) (*domain.Account, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Account) (*domain.Account, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Account) *domain.Account); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Account) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - account domain.Account
func (_e *MockAccountRepository_Expecter) Update(ctx interface{}, account interface{}) *MockAccountRepository_Update_Call {
	return &MockAccountRepository_Update_Call{Call: _e.mock.On("Update", ctx, account)}
}

func (_c *MockAccountRepository_Update_Call) Run(run func(ctx context.Context, account domain.Account)) *MockAccountRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Account
		if args[1] != nil {
			arg1 = args[1].(domain.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Update_Call) Return(account1 *domain.Account, err error) *MockAccountRepository_Update_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountRepository_Update_Call) RunAndReturn(run func(ctx context.Context, account domain.Account) (*domain.Account, error)) *MockAccountRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTransactionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTransactionRepository_Delete_Call {
	return &MockTransactionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTransactionRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockTransactionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Delete_Call) Return(err error) *MockTransactionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockTransactionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetAll(ctx context.Context) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Transaction); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTransactionRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionRepository_Expecter) GetAll(ctx interface{}) *MockTransactionRepository_GetAll_Call {
	return &MockTransactionRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTransactionRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockTransactionRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetAll_Call) Return(transactions []domain.Transaction, err error) *MockTransactionRepository_GetAll_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Transaction, error)) *MockTransactionRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByAccountID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetAllByAccountID(ctx context.Context, accountId int64) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByAccountID")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []domain.Transaction); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetAllByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByAccountID'
type MockTransactionRepository_GetAllByAccountID_Call struct {
	*mock.Call
}

// GetAllByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId int64
func (_e *MockTransactionRepository_Expecter) GetAllByAccountID(ctx interface{}, accountId interface{}) *MockTransactionRepository_GetAllByAccountID_Call {
	return &MockTransactionRepository_GetAllByAccountID_Call{Call: _e.mock.On("GetAllByAccountID", ctx, accountId)}
}

func (_c *MockTransactionRepository_GetAllByAccountID_Call) Run(run func(ctx context.Context, accountId int64)) *MockTransactionRepository_GetAllByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetAllByAccountID_Call) Return(transactions []domain.Transaction, err error) *MockTransactionRepository_GetAllByAccountID_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionRepository_GetAllByAccountID_Call) RunAndReturn(run func(ctx context.Context, accountId int64) ([]domain.Transaction, error)) *MockTransactionRepository_GetAllByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByAccountIDTx provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetAllByAccountIDTx(ctx context.Context, accountId int64) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByAccountIDTx")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []domain.Transaction); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetAllByAccountIDTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByAccountIDTx'
type MockTransactionRepository_GetAllByAccountIDTx_Call struct {
	*mock.Call
}

// GetAllByAccountIDTx is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId int64
func (_e *MockTransactionRepository_Expecter) GetAllByAccountIDTx(ctx interface{}, accountId interface{}) *MockTransactionRepository_GetAllByAccountIDTx_Call {
	return &MockTransactionRepository_GetAllByAccountIDTx_Call{Call: _e.mock.On("GetAllByAccountIDTx", ctx, accountId)}
}

func (_c *MockTransactionRepository_GetAllByAccountIDTx_Call) Run(run func(ctx context.Context, accountId int64)) *MockTransactionRepository_GetAllByAccountIDTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetAllByAccountIDTx_Call) Return(transactions []domain.Transaction, err error) *MockTransactionRepository_GetAllByAccountIDTx_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionRepository_GetAllByAccountIDTx_Call) RunAndReturn(run func(ctx context.Context, accountId int64) ([]domain.Transaction, error)) *MockTransactionRepository_GetAllByAccountIDTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetByID(ctx context.Context, id int64) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTransactionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTransactionRepository_GetByID_Call {
	return &MockTransactionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTransactionRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) Return(transaction *domain.Transaction, err error) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.Transaction, error)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Save(ctx context.Context, transaction domain.Transaction) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, transaction)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) *domain.Transaction); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Transaction) error); ok {
		r1 = returnFunc(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTransactionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction domain.Transaction
func (_e *MockTransactionRepository_Expecter) Save(ctx interface{}, transaction interface{}) *MockTransactionRepository_Save_Call {
	return &MockTransactionRepository_Save_Call{Call: _e.mock.On("Save", ctx, transaction)}
}

func (_c *MockTransactionRepository_Save_Call) Run(run func(ctx context.Context, transaction domain.Transaction)) *MockTransactionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Save_Call) Return(transaction1 *domain.Transaction, err error) *MockTransactionRepository_Save_Call {
	_c.Call.Return(transaction1, err)
	return _c
}

func (_c *MockTransactionRepository_Save_Call) RunAndReturn(run func(ctx context.Context, transaction domain.Transaction) (*domain.Transaction, error)) *MockTransactionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTx provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) SaveTx(ctx context.Context, transaction domain.Transaction) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for SaveTx")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, transaction)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) *domain.Transaction); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Transaction) error); ok {
		r1 = returnFunc(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_SaveTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTx'
type MockTransactionRepository_SaveTx_Call struct {
	*mock.Call
}

// SaveTx is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction domain.Transaction
func (_e *MockTransactionRepository_Expecter) SaveTx(ctx interface{}, transaction interface{}) *MockTransactionRepository_SaveTx_Call {
	return &MockTransactionRepository_SaveTx_Call{Call: _e.mock.On("SaveTx", ctx, transaction)}
}

func (_c *MockTransactionRepository_SaveTx_Call) Run(run func(ctx context.Context, transaction domain.Transaction)) *MockTransactionRepository_SaveTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_SaveTx_Call) Return(transaction1 *domain.Transaction, err error) *MockTransactionRepository_SaveTx_Call {
	_c.Call.Return(transaction1, err)
	return _c
}

func (_c *MockTransactionRepository_SaveTx_Call) RunAndReturn(run func(ctx context.Context, transaction domain.Transaction) (*domain.Transaction, error)) *MockTransactionRepository_SaveTx_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Update(ctx context.Context, transaction domain.Transaction) error {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) error); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction domain.Transaction
func (_e *MockTransactionRepository_Expecter) Update(ctx interface{}, transaction interface{}) *MockTransactionRepository_Update_Call {
	return &MockTransactionRepository_Update_Call{Call: _e.mock.On("Update", ctx, transaction)}
}

func (_c *MockTransactionRepository_Update_Call) Run(run func(ctx context.Context, transaction domain.Transaction)) *MockTransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Update_Call) Return(err error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, transaction domain.Transaction) error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateForBalance provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) UpdateForBalance(ctx context.Context, transaction domain.Transaction) error {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for UpdateForBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) error); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_UpdateForBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateForBalance'
type MockTransactionRepository_UpdateForBalance_Call struct {
	*mock.Call
}

// UpdateForBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction domain.Transaction
func (_e *MockTransactionRepository_Expecter) UpdateForBalance(ctx interface{}, transaction interface{}) *MockTransactionRepository_UpdateForBalance_Call {
	return &MockTransactionRepository_UpdateForBalance_Call{Call: _e.mock.On("UpdateForBalance", ctx, transaction)}
}

func (_c *MockTransactionRepository_UpdateForBalance_Call) Run(run func(ctx context.Context, transaction domain.Transaction)) *MockTransactionRepository_UpdateForBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_UpdateForBalance_Call) Return(err error) *MockTransactionRepository_UpdateForBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_UpdateForBalance_Call) RunAndReturn(run func(ctx context.Context, transaction domain.Transaction) error) *MockTransactionRepository_UpdateForBalance_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateForBalanceTx provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) UpdateForBalanceTx(ctx context.Context, transaction domain.Transaction) error {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for UpdateForBalanceTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) error); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_UpdateForBalanceTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateForBalanceTx'
type MockTransactionRepository_UpdateForBalanceTx_Call struct {
	*mock.Call
}

// UpdateForBalanceTx is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction domain.Transaction
func (_e *MockTransactionRepository_Expecter) UpdateForBalanceTx(ctx interface{}, transaction interface{}) *MockTransactionRepository_UpdateForBalanceTx_Call {
	return &MockTransactionRepository_UpdateForBalanceTx_Call{Call: _e.mock.On("UpdateForBalanceTx", ctx, transaction)}
}

func (_c *MockTransactionRepository_UpdateForBalanceTx_Call) Run(run func(ctx context.Context, transaction domain.Transaction)) *MockTransactionRepository_UpdateForBalanceTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_UpdateForBalanceTx_Call) Return(err error) *MockTransactionRepository_UpdateForBalanceTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_UpdateForBalanceTx_Call) RunAndReturn(run func(ctx context.Context, transaction domain.Transaction) error) *MockTransactionRepository_UpdateForBalanceTx_Call {
	_c.Call.Return(run)
	return _c
}
