// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/alexduzi/challengepismo/internal/infrastructure/config"
	"github.com/alexduzi/challengepismo/internal/infrastructure/http/handler"
	"github.com/alexduzi/challengepismo/internal/infrastructure/logger"
	"github.com/alexduzi/challengepismo/internal/infrastructure/persistence/postgres"
	"github.com/alexduzi/challengepismo/internal/repository"
	"github.com/alexduzi/challengepismo/internal/usecase"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeApplication(cfg *config.Config, db *sqlx.DB, log logger.Logger) *Application {
	accountRepositoryImpl := postgres.NewAccountRepository(db, log)
	accountUseCaseImpl := usecase.NewAccountUseCase(accountRepositoryImpl, log)
	accountHandler := handler.NewAccountHandler(accountUseCaseImpl, log)
	transactionRepositoryImpl := postgres.NewTransactionRepository(db)
	transactionUseCaseImpl := usecase.NewTransactionUseCase(accountRepositoryImpl, transactionRepositoryImpl)
	transactionHandler := handler.NewTransactionHandler(transactionUseCaseImpl)
	healthHandler := handler.NewHealthHandler(cfg)
	application := NewApplication(cfg, log, accountHandler, transactionHandler, healthHandler)
	return application
}

// wire.go:

var setAccountRepositoryDependency = wire.NewSet(postgres.NewAccountRepository, wire.Bind(new(repository.AccountRepository), new(*postgres.AccountRepositoryImpl)))

var setTransactionRepositoryDependency = wire.NewSet(postgres.NewTransactionRepository, wire.Bind(new(repository.TransactionRepository), new(*postgres.TransactionRepositoryImpl)))

var setAccountUseCaseDependency = wire.NewSet(usecase.NewAccountUseCase, wire.Bind(new(usecase.AccountUseCase), new(*usecase.AccountUseCaseImpl)))

var setTransactionUseCaseDependency = wire.NewSet(usecase.NewTransactionUseCase, wire.Bind(new(usecase.TransactionUseCase), new(*usecase.TransactionUseCaseImpl)))

var setHandlerDependency = wire.NewSet(handler.NewAccountHandler, handler.NewTransactionHandler, handler.NewHealthHandler)

var setRepositoryDependency = wire.NewSet(
	setAccountRepositoryDependency,
	setTransactionRepositoryDependency,
)

var setUseCaseDependency = wire.NewSet(
	setAccountUseCaseDependency,
	setTransactionUseCaseDependency,
)
