// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	"github.com/alexduzi/challengepismo/internal/dto/request"
	"github.com/alexduzi/challengepismo/internal/dto/response"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountUseCase creates a new instance of MockAccountUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountUseCase {
	mock := &MockAccountUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountUseCase is an autogenerated mock type for the AccountUseCase type
type MockAccountUseCase struct {
	mock.Mock
}

type MockAccountUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountUseCase) EXPECT() *MockAccountUseCase_Expecter {
	return &MockAccountUseCase_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function for the type MockAccountUseCase
func (_mock *MockAccountUseCase) CreateAccount(ctx context.Context, request1 request.CreateAccountRequest) (*response.AccountResponse, error) {
	ret := _mock.Called(ctx, request1)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *response.AccountResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CreateAccountRequest) (*response.AccountResponse, error)); ok {
		return returnFunc(ctx, request1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CreateAccountRequest) *response.AccountResponse); ok {
		r0 = returnFunc(ctx, request1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AccountResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.CreateAccountRequest) error); ok {
		r1 = returnFunc(ctx, request1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountUseCase_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockAccountUseCase_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - request1 request.CreateAccountRequest
func (_e *MockAccountUseCase_Expecter) CreateAccount(ctx interface{}, request1 interface{}) *MockAccountUseCase_CreateAccount_Call {
	return &MockAccountUseCase_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, request1)}
}

func (_c *MockAccountUseCase_CreateAccount_Call) Run(run func(ctx context.Context, request1 request.CreateAccountRequest)) *MockAccountUseCase_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.CreateAccountRequest
		if args[1] != nil {
			arg1 = args[1].(request.CreateAccountRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountUseCase_CreateAccount_Call) Return(accountResponse *response.AccountResponse, err error) *MockAccountUseCase_CreateAccount_Call {
	_c.Call.Return(accountResponse, err)
	return _c
}

func (_c *MockAccountUseCase_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, request1 request.CreateAccountRequest) (*response.AccountResponse, error)) *MockAccountUseCase_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByID provides a mock function for the type MockAccountUseCase
func (_mock *MockAccountUseCase) GetAccountByID(ctx context.Context, id int64) (*response.AccountResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByID")
	}

	var r0 *response.AccountResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*response.AccountResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *response.AccountResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AccountResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountUseCase_GetAccountByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByID'
type MockAccountUseCase_GetAccountByID_Call struct {
	*mock.Call
}

// GetAccountByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAccountUseCase_Expecter) GetAccountByID(ctx interface{}, id interface{}) *MockAccountUseCase_GetAccountByID_Call {
	return &MockAccountUseCase_GetAccountByID_Call{Call: _e.mock.On("GetAccountByID", ctx, id)}
}

func (_c *MockAccountUseCase_GetAccountByID_Call) Run(run func(ctx context.Context, id int64)) *MockAccountUseCase_GetAccountByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountUseCase_GetAccountByID_Call) Return(accountResponse *response.AccountResponse, err error) *MockAccountUseCase_GetAccountByID_Call {
	_c.Call.Return(accountResponse, err)
	return _c
}

func (_c *MockAccountUseCase_GetAccountByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*response.AccountResponse, error)) *MockAccountUseCase_GetAccountByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionUseCase creates a new instance of MockTransactionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionUseCase {
	mock := &MockTransactionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionUseCase is an autogenerated mock type for the TransactionUseCase type
type MockTransactionUseCase struct {
	mock.Mock
}

type MockTransactionUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionUseCase) EXPECT() *MockTransactionUseCase_Expecter {
	return &MockTransactionUseCase_Expecter{mock: &_m.Mock}
}

// CreateTransaction provides a mock function for the type MockTransactionUseCase
func (_mock *MockTransactionUseCase) CreateTransaction(ctx context.Context, request1 request.CreateTransactionRequest) (*response.TransactionResponse, error) {
	ret := _mock.Called(ctx, request1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 *response.TransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CreateTransactionRequest) (*response.TransactionResponse, error)); ok {
		return returnFunc(ctx, request1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CreateTransactionRequest) *response.TransactionResponse); ok {
		r0 = returnFunc(ctx, request1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.TransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.CreateTransactionRequest) error); ok {
		r1 = returnFunc(ctx, request1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionUseCase_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type MockTransactionUseCase_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - request1 request.CreateTransactionRequest
func (_e *MockTransactionUseCase_Expecter) CreateTransaction(ctx interface{}, request1 interface{}) *MockTransactionUseCase_CreateTransaction_Call {
	return &MockTransactionUseCase_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, request1)}
}

func (_c *MockTransactionUseCase_CreateTransaction_Call) Run(run func(ctx context.Context, request1 request.CreateTransactionRequest)) *MockTransactionUseCase_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.CreateTransactionRequest
		if args[1] != nil {
			arg1 = args[1].(request.CreateTransactionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionUseCase_CreateTransaction_Call) Return(transactionResponse *response.TransactionResponse, err error) *MockTransactionUseCase_CreateTransaction_Call {
	_c.Call.Return(transactionResponse, err)
	return _c
}

func (_c *MockTransactionUseCase_CreateTransaction_Call) RunAndReturn(run func(ctx context.Context, request1 request.CreateTransactionRequest) (*response.TransactionResponse, error)) *MockTransactionUseCase_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}
