// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Alex Duzi",
            "email": "duzihd@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/accounts": {
            "post": {
                "description": "Creates a new account with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Create a new account",
                "parameters": [
                    {
                        "description": "Account creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_request.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Account created successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Document number or email already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/accounts/{accountId}": {
            "get": {
                "description": "Retrieves account details by account ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get account by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Account found",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid account ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions": {
            "post": {
                "description": "Creates a new transaction for an account. Operation types: 1=Purchase, 2=Installment Purchase, 3=Withdrawal, 4=Payment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Create a new transaction",
                "parameters": [
                    {
                        "description": "Transaction creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_request.CreateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Transaction created successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Invalid amount for operation type",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.HealthResponse"
                        }
                    }
                }
            }
        },
        "/readiness": {
            "get": {
                "description": "Returns the health status of the API service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/github_com_alexduzi_challengepismo_internal_dto_response.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_alexduzi_challengepismo_internal_dto_request.CreateAccountRequest": {
            "type": "object",
            "required": [
                "account_type",
                "document_number",
                "email",
                "full_name",
                "phone"
            ],
            "properties": {
                "account_type": {
                    "type": "string",
                    "enum": [
                        "checking",
                        "savings"
                    ],
                    "example": "checking"
                },
                "document_number": {
                    "type": "string",
                    "example": "12345678900"
                },
                "email": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "joao.silva@example.com"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "João da Silva"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 10,
                    "example": "11987654321"
                }
            }
        },
        "github_com_alexduzi_challengepismo_internal_dto_request.CreateTransactionRequest": {
            "type": "object",
            "required": [
                "account_id",
                "amount",
                "operation_type_id"
            ],
            "properties": {
                "account_id": {
                    "type": "integer",
                    "example": 1
                },
                "amount": {
                    "type": "number",
                    "example": 100.5
                },
                "operation_type_id": {
                    "type": "integer",
                    "maximum": 4,
                    "minimum": 1,
                    "example": 4
                }
            }
        },
        "github_com_alexduzi_challengepismo_internal_dto_response.AccountResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer",
                    "example": 1
                },
                "account_type": {
                    "type": "string",
                    "example": "checking"
                },
                "balance": {
                    "type": "number",
                    "example": 1500.5
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T10:00:00Z"
                },
                "document_number": {
                    "type": "string",
                    "example": "12345678900"
                },
                "email": {
                    "type": "string",
                    "example": "joao.silva@example.com"
                },
                "full_name": {
                    "type": "string",
                    "example": "João da Silva"
                },
                "phone": {
                    "type": "string",
                    "example": "11987654321"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T10:00:00Z"
                }
            }
        },
        "github_com_alexduzi_challengepismo_internal_dto_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "validation error: invalid input"
                }
            }
        },
        "github_com_alexduzi_challengepismo_internal_dto_response.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "api-account"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "github_com_alexduzi_challengepismo_internal_dto_response.TransactionResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer",
                    "example": 1
                },
                "amount": {
                    "type": "number",
                    "example": 100.5
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T10:00:00Z"
                },
                "event_date": {
                    "type": "string",
                    "example": "2024-01-01T10:00:00Z"
                },
                "operation": {
                    "type": "integer",
                    "example": 4
                },
                "transaction_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Accounts API",
	Description:      "API for creating/fetching accounts and transactions",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
